"""empty message

Revision ID: 1255c408dd21
Revises: c2b13f255513
Create Date: 2024-07-08 00:03:55.846136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1255c408dd21'
down_revision = 'c2b13f255513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_reports', schema=None) as batch_op:
        batch_op.alter_column('content_json',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.alter_column('content_json',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.alter_column('content_json',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('course_reports', schema=None) as batch_op:
        batch_op.alter_column('content_json',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
