"""empty message

Revision ID: 422d0e9b03b9
Revises: f0d30fad5188
Create Date: 2024-08-01 15:18:32.354971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d0e9b03b9'
down_revision = 'f0d30fad5188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
