"""fix _password_hash bug

Revision ID: 638785530d0b
Revises: 268377cac88e
Create Date: 2024-06-20 12:44:12.945380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638785530d0b'
down_revision = '268377cac88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=60), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
