"""add content_json column to reports tables

Revision ID: c2b13f255513
Revises: d457c7360fc3
Create Date: 2024-07-07 23:58:12.908119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b13f255513'
down_revision = 'd457c7360fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.JSON(), nullable=False))

    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.drop_column('content_json')

    with op.batch_alter_table('course_reports', schema=None) as batch_op:
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###
