"""change users_courses, users_roles, students_courses to class definitions

Revision ID: d457c7360fc3
Revises: 000e886d845f
Create Date: 2024-06-25 12:21:57.603420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd457c7360fc3'
down_revision = '000e886d845f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_courses', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_students_courses_student_id'), ['student_id', 'course_id'])

    with op.batch_alter_table('users_courses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_courses_user_id'), ['user_id', 'course_id'])

    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_roles_user_id'), ['user_id', 'role_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_roles_user_id'), type_='unique')
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users_courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_courses_user_id'), type_='unique')
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('students_courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_students_courses_student_id'), type_='unique')
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
